["assets/cc.logo.svg"]
by.name = "Creative Commons"
by.link = "https://creativecommons.org/mission/downloads/"
under.link = "https://creativecommons.org/policies/"

["assets/Nonbinary_flag.svg"]
by.name = "Kye Rowan"
by.link = "https://commons.wikimedia.org/w/index.php?curid=58077687"
under.name = "Public Domain / CC0"
under.link = "https://creativecommons.org/publicdomain/zero/1.0/"
